### PR TITLE
[WIP] Adding all the supporting helper yamls

### PR DESCRIPTION
**Pull request by juliancheal**
Hank Venture: Ma Venture didn't raise no fools.

### CODE REVIEW

**Comment by julianchealtest** [comment]
<rubocop />Checked commit https://github.com/HumanoidElectricLabPartnerRobot/hank/commit/bd2c39e3dba054811895f647a1b98bcc62861b7d with ruby 2.5.3, rubocop 0.52.1, haml-lint 0.28.0, and yamllint 1.15.0
1 file checked, 2 offenses detected

**Gemfile**
- [ ] :exclamation: - [Line 12](https://github.com/HumanoidElectricLabPartnerRobot/hank/blob/bd2c39e3dba054811895f647a1b98bcc62861b7d/Gemfile#L12), Col 19 - [Layout/ExtraSpacing](http://rubydoc.info/gems/rubocop/0.52.1/RuboCop/Cop/Layout/ExtraSpacing) - Unnecessary spacing detected.
- [ ] :exclamation: - [Line 3](https://github.com/HumanoidElectricLabPartnerRobot/hank/blob/bd2c39e3dba054811895f647a1b98bcc62861b7d/Gemfile#L3), Col 21 - [Layout/ExtraSpacing](http://rubydoc.info/gems/rubocop/0.52.1/RuboCop/Cop/Layout/ExtraSpacing) - Unnecessary spacing detected.

**Comment by juliancheal** [comment]
@julianchealtest assign @juliancheal

**Comment by juliancheal** [comment]
@julianchealtest add_label bug

**Comment by juliancheal** [comment]
@julianchealtest add_label wip

**Comment by juliancheal** [comment]
@julianchealtest add_lable wip

**Pull request closed without merging**
